out. 07, 2024 7:22:06 PM net.sf.l2j.gameserver.autofarm.AutoFarmData restorePlayer
SEVERE: Não foi possível restaurar as AutoFarmArea do player HighLander.
java.sql.SQLSyntaxErrorException: (conn=7514) Table 'l2jbrazuca.autofarm_nodes' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at net.sf.l2j.gameserver.autofarm.AutoFarmData.restorePlayer(AutoFarmData.java:76)
	at net.sf.l2j.gameserver.autofarm.AutoFarmManager.onPlayerLogin(AutoFarmManager.java:115)
	at net.sf.l2j.gameserver.model.actor.Player.onPlayerEnter(Player.java:6644)
	at net.sf.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:319)
	at net.sf.l2j.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:45)
	at net.sf.l2j.commons.pool.ThreadPool$TaskWrapper.run(ThreadPool.java:219)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'l2jbrazuca.autofarm_nodes' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 11 more
Caused by: java.sql.SQLException: Table 'l2jbrazuca.autofarm_nodes' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1683)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1545)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1508)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 12 more

